version: '3'

services:
    mysql:
        image: mysql
        container_name: db-mysql
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: LCTH_Dev
            MYSQL_USER: lcth-dev
            MYSQL_PASSWORD: password
        volumes:
            - "var/lib/mysql"
        expose: 
            - "3306"
    node:
        build: .
        ports:
            - "8080:8080"
        expose:
            - "8080"
        restart: always
        links:
            - mysql
        depends_on: 
            - mysql

    
